// Ortak Sepet - shared category rules.
// Loaded by both the popup and the background script so a product added from the
// context menu is categorised exactly like one added from the popup.

function normalizeForCategory(text) {
  return String(text || "")
    .toLocaleLowerCase("tr-TR")
    .replace(/ı/g, "i")
    .replace(/ğ/g, "g")
    .replace(/ü/g, "u")
    .replace(/ş/g, "s")
    .replace(/ö/g, "o")
    .replace(/ç/g, "c");
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function includesKeyword(text, keyword) {
  const normalizedKeyword = normalizeForCategory(keyword);

  if (!normalizedKeyword) return false;

  const isShortKeyword = normalizedKeyword.length <= 3;
  const isSingleWord = !normalizedKeyword.includes(" ");

  if (isShortKeyword && isSingleWord) {
    const regex = new RegExp(
      `(^|[^a-z0-9])${escapeRegex(normalizedKeyword)}($|[^a-z0-9])`,
      "i",
    );

    return regex.test(text);
  }

  return text.includes(normalizedKeyword);
}

function includesAny(text, keywords) {
  return keywords.some((keyword) => includesKeyword(text, keyword));
}

// Rule order matters: the first match wins. Specific categories (phone,
// computer) are checked before the broader "Elektronik" rule so that a phone
// case or a graphics card does not get pulled into general electronics.
const CATEGORY_RULES = [
  {
    category: "Anne & Bebek",
    keywords: [
      "bebek",
      "mama",
      "devam sutu",
      "bebelac",
      "aptamil",
      "sma",
      "bez",
      "islak mendil",
      "emzik",
      "biberon",
      "oyuncak bebek",
      "baby",
      "nappy",
      "nappies",
      "pushchair",
      "pram",
      "baby wipes",
    ],
  },
  {
    category: "İçecek",
    keywords: [
      "red bull",
      "enerji icecegi",
      "icecek",
      "kola",
      "gazoz",
      "su",
      "soda",
      "kahve",
      "cay",
      "meyve suyu",
      "energy drink",
      "coffee",
      "tea",
      "juice",
      "sparkling water",
    ],
  },
  {
    category: "Telefon & Aksesuar",
    keywords: [
      "iphone",
      "android",
      "telefon",
      "kilif",
      "kılıf",
      "ekran koruyucu",
      "spigen",
      "magsafe",
      "airpods",
      "watch",
      "akilli saat",
      "akıllı saat",
      "smartphone",
      "mobile phone",
      "phone case",
      "screen protector",
      "smartwatch",
      "earbuds",
    ],
  },
  {
    category: "Bilgisayar",
    keywords: [
      "islemci",
      "işlemci",
      "anakart",
      "ram",
      "ekran karti",
      "ekran kartı",
      "ryzen",
      "intel",
      "nvidia",
      "amd",
      "rtx",
      "ddr5",
      "psu",
      "kasa",
      "fan",
      "sogutucu",
      "soğutucu",
      "processor",
      "motherboard",
      "graphics card",
      "gpu",
      "cpu cooler",
      "power supply",
    ],
  },
  {
    category: "Elektronik",
    keywords: [
      "usb",
      "bellek",
      "ssd",
      "hdd",
      "harddisk",
      "kulaklik",
      "mouse",
      "klavye",
      "monitor",
      "laptop",
      "notebook",
      "tablet",
      "kamera",
      "sandisk",
      "kingston",
      "logitech",
      "anker",
      "powerbank",
      "sarj",
      "şarj",
      "adaptör",
      "adapter",
      "kablo",
      "hdmi",
      "galaxy tab",
      "headphones",
      "keyboard",
      "charger",
      "cable",
      "camera",
      "television",
      "soundbar",
    ],
  },
  {
    category: "Ev & Yaşam",
    keywords: [
      "ev",
      "mutfak",
      "banyo",
      "koltuk",
      "masa",
      "sandalye",
      "hali",
      "halı",
      "lamba",
      "nevresim",
      "yastik",
      "yastık",
      "dekorasyon",
      "supurge",
      "süpürge",
      "tencere",
      "tabak",
      "bardak",
      "dolap",
      "raf",
      "kitaplik",
      "kitaplık",
      "gardirop",
      "gardırop",
      "cekmece",
      "çekmece",
      "komodin",
      "yatak",
      "perde",
      "mum",
      "saksi",
      "saksı",
      "dik supurge",
      "dik süpürge",
      "kablolu supurge",
      "kablosuz supurge",
      "powercyclone",
      "kitchen",
      "bathroom",
      "sofa",
      "armchair",
      "table",
      "chair",
      "wardrobe",
      "bookcase",
      "shelf",
      "shelving",
      "chest of drawers",
      "bedside table",
      "mattress",
      "duvet",
      "cushion",
      "curtain",
      "rug",
      "lamp",
      "candle",
      "storage box",
      "vacuum cleaner",
    ],
  },
  {
    category: "Kişisel Bakım",
    keywords: [
      "sampuan",
      "şampuan",
      "parfum",
      "parfüm",
      "deodorant",
      "dis macunu",
      "diş macunu",
      "tirnak",
      "tırnak",
      "sac",
      "saç",
      "cilt",
      "krem",
      "tras",
      "tıraş",
      "tiras",
      "makyaj",
      "kozmetik",
      "shampoo",
      "perfume",
      "fragrance",
      "toothpaste",
      "skincare",
      "moisturiser",
      "moisturizer",
      "makeup",
      "cosmetics",
      "shaving",
    ],
  },
  {
    category: "Giyim",
    keywords: [
      "tisort",
      "tişört",
      "gomlek",
      "gömlek",
      "pantolon",
      "ayakkabi",
      "ayakkabı",
      "mont",
      "ceket",
      "elbise",
      "kazak",
      "sweatshirt",
      "corap",
      "çorap",
      "t-shirt",
      "tshirt",
      "shirt",
      "trousers",
      "jeans",
      "hoodie",
      "jacket",
      "dress",
      "leggings",
      "shorts",
      "trainers",
      "socks",
    ],
  },
  {
    category: "Kitap & Kırtasiye",
    keywords: [
      "kitap",
      "roman",
      "defter",
      "kalem",
      "kirtasiye",
      "kırtasiye",
      "ajanda",
      "silgi",
      "dosya",
      "book",
      "novel",
      "notebook paper",
      "stationery",
      "pen",
      "pencil",
      "diary",
    ],
  },
  {
    category: "Market",
    keywords: [
      "gida",
      "gıda",
      "makarna",
      "pirinc",
      "pirinç",
      "un",
      "seker",
      "şeker",
      "cikolata",
      "çikolata",
      "biskuvi",
      "bisküvi",
      "cips",
      "sut",
      "süt",
      "peynir",
      "zeytin",
      "yag",
      "yağ",
      "temizlik",
      "pasta",
      "rice",
      "sugar",
      "chocolate",
      "biscuit",
      "crisps",
      "milk",
      "cheese",
      "olive oil",
      "cleaning",
    ],
  },
  {
    category: "Oyuncak",
    keywords: [
      "oyuncak",
      "lego",
      "puzzle",
      "pelus",
      "peluş",
      "figür",
      "figur",
      "araba oyuncak",
      "toy",
      "jigsaw",
      "board game",
      "plush",
      "action figure",
    ],
  },
  {
    category: "Otomotiv",
    keywords: [
      "araba",
      "oto",
      "otomobil",
      "lastik",
      "motor yagi",
      "motor yağı",
      "silecek",
      "akü",
      "aku",
      "jant",
      "car tyre",
      "tyre",
      "engine oil",
      "windscreen",
      "car battery",
    ],
  },
];

function categorizeProduct(item) {
  const text = normalizeForCategory(`${item?.title || ""} ${item?.site || ""}`);

  const matchedRule = CATEGORY_RULES.find((rule) =>
    includesAny(text, rule.keywords),
  );

  return matchedRule ? matchedRule.category : "Diğer";
}
