// Ortak Sepet popup module: config.js
// This file was split from popup.js so popup logic can be maintained by responsibility.

// Sepet anahtarı shared/cart.js içinde; popup depoya oradan erişir.
const VIEW_MODE_KEY = "ortakSepetViewMode";
// Alınan ürünler ayrı anahtarda: rozet sayısı, toplamlar ve fiyat güncellemesi
// yalnızca sepeti okuduğu için alınanlar bu akışların hiçbirine karışmıyor.
const PURCHASED_KEY = "ortakSepetPurchased";
const UNDO_KEY = "ortakSepetUndo";
// Geri alma teklifi bu süre boyunca geçerli; popup kapanıp açılsa da durur.
const UNDO_WINDOW_MS = 5 * 60 * 1000;
const COMPACT_MODE_KEY = "ortakSepetCompactMode";
const LANGUAGE_KEY = "ortakSepetLanguage";
const THEME_KEY = "ortakSepetTheme";

const addCurrentProductBtn = document.getElementById("addCurrentProductBtn");
const categorizeProductsBtn = document.getElementById("categorizeProductsBtn");
const installmentProductsBtn = document.getElementById(
  "installmentProductsBtn",
);
const updateAllPricesBtn = document.getElementById("updateAllPricesBtn");
const exportCsvBtn = document.getElementById("exportCsvBtn");
const copyCartBtn = document.getElementById("copyCartBtn");
const undoBtn = document.getElementById("undoBtn");
const compactViewBtn = document.getElementById("compactViewBtn");
const countryGroupingBtn = document.getElementById("countryGroupingBtn");
const clearCartBtn = document.getElementById("clearCartBtn");
const statusEl = document.getElementById("status");
const cartItemsEl = document.getElementById("cartItems");
const totalPriceEl = document.getElementById("totalPrice");
const selectedTotalPriceEl = document.getElementById("selectedTotalPrice");
const itemCountEl = document.getElementById("itemCount");
const languageToggleBtn = document.getElementById("languageToggleBtn");
const languageControlEl = document.getElementById("languageControl");
const themeToggleBtn = document.getElementById("themeToggleBtn");
const appSubtitleEl = document.getElementById("appSubtitle");
const itemCountLabelEl = document.getElementById("itemCountLabel");
const totalPriceLabelEl = document.getElementById("totalPriceLabel");
const selectedTotalPriceLabelEl = document.getElementById("selectedTotalPriceLabel");
const actionGridEl = document.getElementById("actionGrid");
const summarySectionEl = document.getElementById("summarySection");
const footerActionsEl = document.getElementById("footerActions");
const cartTabBtn = document.getElementById("cartTabBtn");
const purchasedTabBtn = document.getElementById("purchasedTabBtn");
const cartPanelEl = document.getElementById("cartPanel");
const purchasedPanelEl = document.getElementById("purchasedPanel");
const purchasedItemsEl = document.getElementById("purchasedItems");
const purchasedSummaryEl = document.getElementById("purchasedSummary");
const markPurchasedBtn = document.getElementById("markPurchasedBtn");

const I18N = {
  tr: {
    appSubtitle: "Alışverişte ortak sepetiniz",
    cartActions: "Sepet işlemleri",
    language: "Dil",
    switchToEnglish: "İngilizceye Geç",
    switchToTurkish: "Türkçeye Geç",
    enableDarkMode: "Karanlık Mod",
    enableLightMode: "Aydınlık Mod",
    addCurrentProduct: "Bu Ürünü Ekle",
    categorizeProducts: "Kategorize Et",
    removeCategories: "Kategorileri Kaldır",
    installmentProducts: "Taksit / Finance",
    removeInstallmentGrouping: "Taksit Grubunu Kaldır",
    updateAllPrices: "Fiyatları Güncelle",
    updating: "Güncelleniyor...",
    cancelUpdate: "Güncellemeyi Durdur",
    pricesUpdateCancelled: "Güncelleme durduruldu. {changed} ürünün fiyatı değişti, {failed} ürün güncellenemedi.",
    exportCsv: "CSV / Excel",
    tabPurchased: "Aldıklarım",
    markPurchased: "Alındı",
    markSelectedPurchased: "Seçilenleri Alındı İşaretle",
    markPurchasedLabel: "Alındı olarak işaretle: {title}",
    purchasedMoved: "{count} ürün alınanlara taşındı.",
    noSelectedItems: "Seçili ürün yok.",
    restoreToCart: "Sepete Geri Al",
    restoreToCartLabel: "Sepete geri al: {title}",
    deletePurchase: "Kaydı Sil",
    deletePurchaseLabel: "Kaydı sil: {title}",
    purchaseRestored: "Ürün sepete geri alındı.",
    purchaseDeleted: "Kayıt silindi.",
    emptyPurchased: "Henüz alınmış ürün yok. Sepetteki bir üründe “Alındı” butonuna bastığında burada ay ay listelenir.",
    purchasedThisMonth: "Bu ay",
    purchasedAllTime: "Tümü",
    purchasedOn: "Alınma",
    copyCart: "Sepeti Kopyala",
    cartCopied: "Sepet panoya kopyalandı.",
    copyFailed: "Sepet kopyalanamadı.",
    copyHeader: "Ortak Sepet — {count} ürün",
    copyTotal: "Toplam: {total}",
    selectItemLabel: "Seçili toplama dahil et: {title}",
    decreaseQuantityLabel: "Adet azalt: {title}",
    increaseQuantityLabel: "Adet artır: {title}",
    openLinkLabel: "Ürün sayfasını aç: {title}",
    manualPriceLabel: "Manuel fiyat gir: {title}",
    removeLabel: "Ürünü sil: {title}",
    clearCartConfirm: "Sepetin tamamı silinecek. Onaylamak için tekrar tıkla.",
    clearCartConfirmButton: "Emin misin?",
    undo: "Geri Al",
    undoDone: "Son işlem geri alındı.",
    undoUnavailable: "Geri alınacak işlem yok.",
    compactView: "Kompakt Görünüm",
    normalView: "Normal Görünüm",
    countryGrouping: "Ülkeye Göre Grupla",
    removeCountryGrouping: "Ülke Gruplamasını Kaldır",
    clearCart: "Sepeti Temizle",
    itemCount: "Ürün sayısı",
    total: "Genel toplam",
    selectedTotal: "Seçili toplam",
    cart: "Sepet",
    emptyCart: "Sepet boş. Desteklenen bir ürün sayfasına giderek ürün ekleyebilirsiniz.",
    selectedTotalTitle: "Seçili toplama dahil et",
    noProductTitle: "Ürün adı yok",
    unknownSite: "Bilinmeyen site",
    priceReadFailed: "Fiyat okunamadı",
    priceUnavailable: "Ana fiyat yok",
    stockStatus: "Durum",
    noActiveOffer: "Satışta değil / satın alma seçeneklerinde",
    subtotalNotIncluded: "Ara toplam: Toplama dahil edilmedi",
    productAddedWithoutPrice: "Ürün eklendi, ancak ana satış fiyatı bulunamadı. Fiyat toplama dahil edilmedi.",
    site: "Site",
    price: "Fiyat",
    source: "Kaynak",
    manual: "Manuel",
    previous: "Önceki",
    installment: "Taksit",
    finance: "Finansman",
    delivery: "Kargo",
    check: "Kontrol",
    available: "Var",
    unavailable: "Yok",
    unknown: "Bilinmiyor",
    freeDelivery: "Ücretsiz kargo",
    deliveryInfoAvailable: "Kargo/teslimat bilgisi var",
    calculatedAtCheckout: "Sepette hesaplanır",
    subtotalUnavailable: "Ara toplam hesaplanamadı",
    subtotal: "Ara toplam: {total}",
    lastFailed: "Başarısız",
    lastManual: "Manuel",
    lastManualKept: "Manuel korundu",
    lastUnavailable: "Ana fiyat yok",
    lastSuccess: "Başarılı",
    quantity: "Adet: {quantity}",
    goToLink: "Linke Git",
    manualPrice: "Manuel Fiyat Gir",
    remove: "Sil",
    installmentAvailableGroup: "Taksit / Finance Var",
    installmentUnavailableGroup: "Taksit / Finance Yok / Bilinmiyor",
    productMeta: "{products} ürün • {quantity} adet • {total}",
    countryTurkey: "Türkiye",
    countryUnitedKingdom: "İngiltere",
    groupedByCountry: "Ürünler ülkeye göre gruplandı.",
    countryGroupingRemoved: "Ülke gruplaması kaldırıldı.",
    readingProduct: "Ürün okunuyor...",
    activeTabMissing: "Aktif sekme bulunamadı.",
    productReadFailed: "Bu sayfadan ürün okunamadı.",
    unsupportedPage: "Bu sayfada eklenti çalışmıyor olabilir. Desteklenen bir ürün sayfasında dene.",
    duplicateAdded: "Bu ürün zaten vardı, adedi artırıldı ve seçili yapıldı.",
    productAdded: "Ürün sepete eklendi.",
    noItemsToCategorize: "Kategorize edilecek ürün yok.",
    categoriesRemoved: "Kategoriler silindi.",
    categoriesApplied: "Ürünler kategorilere ayrıldı.",
    noItemsToGroup: "Gruplanacak ürün yok.",
    groupingRemoved: "Taksit/finance gruplaması kaldırıldı.",
    groupedByPayment: "Ürünler taksit/finance durumuna göre gruplandı.",
    noItemsToUpdate: "Güncellenecek ürün yok.",
    pricesUpdating: "Fiyatlar güncelleniyor...",
    pricesUpdatingProgress: "Fiyatlar güncelleniyor: {current}/{total}",
    pricesUpdateFailed: "Fiyatlar güncellenemedi.",
    pricesUpdateDone: "Güncelleme tamamlandı. {changed} ürünün fiyatı değişti, {failed} ürün güncellenemedi.",
    pricesUpdateError: "Güncelleme sırasında hata oluştu.",
    promptNewPrice: "Yeni fiyatı gir:",
    invalidPrice: "Geçerli bir fiyat girilmedi.",
    manualPriceUpdated: "Fiyat manuel olarak güncellendi.",
    productRemoved: "Ürün silindi.",
    quantityZeroRemoved: "Adet 0 oldu, ürün silindi.",
    csvNoItems: "Dışa aktarılacak ürün yok.",
    csvExported: "Sepet CSV olarak dışa aktarıldı. Excel ile açabilirsiniz.",
    cartCleared: "Sepet temizlendi.",
    yes: "Evet",
    no: "Hayır",
    csvProductName: "Ürün Adı",
    csvSite: "Site",
    csvPrice: "Fiyat",
    csvQuantity: "Adet",
    csvSubtotal: "Ara Toplam",
    csvCurrency: "Para Birimi",
    csvCategory: "Kategori",
    csvPaymentPlan: "Taksit / Finance",
    csvDelivery: "Kargo / Teslimat",
    csvManualPrice: "Manuel Fiyat",
    csvUrl: "URL",
  },
  en: {
    appSubtitle: "Your shared shopping basket",
    cartActions: "Basket actions",
    language: "Language",
    switchToEnglish: "Switch to English",
    switchToTurkish: "Switch to Turkish",
    enableDarkMode: "Dark Mode",
    enableLightMode: "Light Mode",
    addCurrentProduct: "Add This Product",
    categorizeProducts: "Categorise",
    removeCategories: "Remove Categories",
    installmentProducts: "Instalments / Finance",
    removeInstallmentGrouping: "Remove Finance Group",
    updateAllPrices: "Refresh Prices",
    updating: "Updating...",
    cancelUpdate: "Stop Refreshing",
    pricesUpdateCancelled: "Refresh stopped. {changed} product prices changed, {failed} products could not be refreshed.",
    exportCsv: "CSV / Excel",
    tabPurchased: "Purchased",
    markPurchased: "Bought",
    markSelectedPurchased: "Mark Selected as Bought",
    markPurchasedLabel: "Mark as bought: {title}",
    purchasedMoved: "{count} products moved to purchased.",
    noSelectedItems: "No products are selected.",
    restoreToCart: "Move to Basket",
    restoreToCartLabel: "Move back to basket: {title}",
    deletePurchase: "Delete Record",
    deletePurchaseLabel: "Delete record: {title}",
    purchaseRestored: "Product moved back to the basket.",
    purchaseDeleted: "Record deleted.",
    emptyPurchased: "Nothing purchased yet. Press “Bought” on a basket item and it will be listed here month by month.",
    purchasedThisMonth: "This month",
    purchasedAllTime: "All time",
    purchasedOn: "Bought on",
    copyCart: "Copy Basket",
    cartCopied: "Basket copied to the clipboard.",
    copyFailed: "The basket could not be copied.",
    copyHeader: "Ortak Sepet — {count} products",
    copyTotal: "Total: {total}",
    selectItemLabel: "Include in selected total: {title}",
    decreaseQuantityLabel: "Decrease quantity: {title}",
    increaseQuantityLabel: "Increase quantity: {title}",
    openLinkLabel: "Open product page: {title}",
    manualPriceLabel: "Enter manual price: {title}",
    removeLabel: "Remove product: {title}",
    clearCartConfirm: "This will remove every product. Click again to confirm.",
    clearCartConfirmButton: "Are you sure?",
    undo: "Undo",
    undoDone: "Last action undone.",
    undoUnavailable: "There is nothing to undo.",
    compactView: "Compact View",
    normalView: "Normal View",
    countryGrouping: "Group by Country",
    removeCountryGrouping: "Remove Country Grouping",
    clearCart: "Clear Basket",
    itemCount: "Item count",
    total: "Total",
    selectedTotal: "Selected total",
    cart: "Basket",
    emptyCart: "Your basket is empty. Open a supported product page to add an item.",
    selectedTotalTitle: "Include in selected total",
    noProductTitle: "No product title",
    unknownSite: "Unknown site",
    priceReadFailed: "Price could not be read",
    priceUnavailable: "No main price",
    stockStatus: "Status",
    noActiveOffer: "Unavailable / buying options only",
    subtotalNotIncluded: "Subtotal: Not included in total",
    productAddedWithoutPrice: "Product added, but the main selling price was not available. It was not included in totals.",
    site: "Site",
    price: "Price",
    source: "Source",
    manual: "Manual",
    previous: "Previous",
    installment: "Instalments",
    finance: "Finance",
    delivery: "Delivery",
    check: "Check",
    available: "Available",
    unavailable: "Unavailable",
    unknown: "Unknown",
    freeDelivery: "Free delivery",
    deliveryInfoAvailable: "Delivery information available",
    calculatedAtCheckout: "Calculated at checkout",
    subtotalUnavailable: "Subtotal could not be calculated",
    subtotal: "Subtotal: {total}",
    lastFailed: "Failed",
    lastManual: "Manual",
    lastManualKept: "Manual kept",
    lastUnavailable: "No main price",
    lastSuccess: "Successful",
    quantity: "Qty: {quantity}",
    goToLink: "Open Link",
    manualPrice: "Enter Manual Price",
    remove: "Remove",
    installmentAvailableGroup: "Instalments / Finance Available",
    installmentUnavailableGroup: "No Instalments / Finance / Unknown",
    productMeta: "{products} products • {quantity} items • {total}",
    countryTurkey: "Türkiye",
    countryUnitedKingdom: "United Kingdom",
    groupedByCountry: "Products grouped by country.",
    countryGroupingRemoved: "Country grouping removed.",
    readingProduct: "Reading product...",
    activeTabMissing: "Active tab could not be found.",
    productReadFailed: "Product could not be read from this page.",
    unsupportedPage: "The extension may not work on this page. Try a supported product page.",
    duplicateAdded: "This product was already in the basket, so its quantity was increased and selected.",
    productAdded: "Product added to basket.",
    noItemsToCategorize: "There are no products to categorise.",
    categoriesRemoved: "Categories removed.",
    categoriesApplied: "Products categorised.",
    noItemsToGroup: "There are no products to group.",
    groupingRemoved: "Instalment/finance grouping removed.",
    groupedByPayment: "Products grouped by instalment/finance availability.",
    noItemsToUpdate: "There are no products to refresh.",
    pricesUpdating: "Refreshing prices...",
    pricesUpdatingProgress: "Refreshing prices: {current}/{total}",
    pricesUpdateFailed: "Prices could not be refreshed.",
    pricesUpdateDone: "Refresh complete. {changed} product prices changed, {failed} products could not be refreshed.",
    pricesUpdateError: "An error occurred while refreshing prices.",
    promptNewPrice: "Enter a new price:",
    invalidPrice: "A valid price was not entered.",
    manualPriceUpdated: "Price updated manually.",
    productRemoved: "Product removed.",
    quantityZeroRemoved: "Quantity reached 0, product removed.",
    csvNoItems: "There are no products to export.",
    csvExported: "Basket exported as CSV. You can open it with Excel.",
    cartCleared: "Basket cleared.",
    yes: "Yes",
    no: "No",
    csvProductName: "Product Name",
    csvSite: "Site",
    csvPrice: "Price",
    csvQuantity: "Quantity",
    csvSubtotal: "Subtotal",
    csvCurrency: "Currency",
    csvCategory: "Category",
    csvPaymentPlan: "Instalments / Finance",
    csvDelivery: "Delivery",
    csvManualPrice: "Manual Price",
    csvUrl: "URL",
  },
};

const CATEGORY_LABELS = {
  en: {
    "Anne & Bebek": "Mother & Baby",
    "İçecek": "Drinks",
    "Elektronik": "Electronics",
    "Telefon & Aksesuar": "Phone & Accessories",
    "Bilgisayar": "Computers",
    "Ev & Yaşam": "Home & Living",
    "Kişisel Bakım": "Personal Care",
    "Giyim": "Clothing",
    "Kitap & Kırtasiye": "Books & Stationery",
    "Market": "Groceries",
    "Oyuncak": "Toys",
    "Otomotiv": "Automotive",
    "Diğer": "Other",
  },
};

let currentLanguage = "tr";
let currentTheme = "light";
